#!/usr/bin/env python3
"""Build the "optimized" sprite copies used by the game's default image quality.

Originals in assets/sprites/<asset>/ are never modified. For every set listed in
assets/sprites/index.json this writes assets/sprites-opt/<asset>/ with:
  - every frame downscaled so the character's body is at most TARGET_BODY px tall
    (the game draws characters ~180 px tall at 1080p, ~230 px at the largest), and
  - every portrait downscaled to PORTRAIT px (HUD chips draw them <= ~90 px).
The game keeps reading coordinates (anchors, landmarks) from the original
sprites.json and simply draws each optimized frame at the original frame size,
so no manifest needs rewriting. assets/sprites-opt/index.json records the scale
per set. Re-run after any sprite intake:

    python3 party/tools/sprites/optimize.py            # all sets
    python3 party/tools/sprites/optimize.py fox snowstar

validate.py warns when a set's optimized copy is missing or stale (the
fingerprint of its sources changed). The game also falls back to the original
image for any optimized frame that fails to load.
"""
import hashlib, json, sys
from pathlib import Path
from PIL import Image

TARGET_BODY = 240
PORTRAIT = 192
ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'assets' / 'sprites'
DST = ROOT / 'assets' / 'sprites-opt'


def save(im, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    im.save(path, 'WEBP', quality=88, method=4)


def fingerprint(asset):
    """Hash of the set's manifest and every source file (name + bytes)."""
    h = hashlib.sha1()
    folder = SRC / asset
    for f in sorted([folder / 'sprites.json', *folder.glob('*.webp')]):
        h.update(f.name.encode()); h.update(f.read_bytes())
    return h.hexdigest()[:16]


def build(asset):
    m = json.loads((SRC / asset / 'sprites.json').read_text())
    k = min(1.0, TARGET_BODY / float(m['bodyHeight']))
    portraits = set((m.get('portraits') or {}).values())
    out = DST / asset
    count = 0
    for f in sorted((SRC / asset).glob('*.webp')):
        im = Image.open(f).convert('RGBA')
        if f.name in portraits or f.name.startswith('portrait'):
            s = min(1.0, PORTRAIT / max(im.size))
        else:
            s = k
        if s < 1.0:
            im = im.resize((max(1, round(im.width * s)), max(1, round(im.height * s))), Image.LANCZOS)
        save(im, out / f.name)
        count += 1
    # Drop optimized files whose originals were removed.
    names = {f.name for f in (SRC / asset).glob('*.webp')}
    for f in out.glob('*.webp'):
        if f.name not in names: f.unlink()
    return {'scale': round(k, 5), 'portrait': PORTRAIT, 'source': fingerprint(asset)}, count


def main(argv):
    sets = json.loads((SRC / 'index.json').read_text()).get('sets', [])
    only = argv[1:] or sets
    idx_path = DST / 'index.json'
    idx = json.loads(idx_path.read_text()) if idx_path.exists() else {'sets': {}}
    for a in only:
        if a not in sets:
            print('skip (not indexed):', a); continue
        info, n = build(a)
        idx['sets'][a] = info
        print(f'{a}: {n} files, frame scale {info["scale"]}')
    idx['sets'] = {a: v for a, v in idx['sets'].items() if a in sets}
    idx['note'] = 'Generated by tools/sprites/optimize.py; do not edit by hand.'
    DST.mkdir(parents=True, exist_ok=True)
    idx_path.write_text(json.dumps(idx, indent=1) + '\n')


if __name__ == '__main__':
    main(sys.argv)
